# MediaWiki with MySQL
version: '3'
services:
  web:
    image: mediawiki
    container_name: MediaWiki
    restart: always
    ports:
      - 80:80
    links:
      - database
    volumes:
      - ./images:/var/www/html/images
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php
    networks:
      - docker_network
  database:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: wiki
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wikimedia
      MYSQL_PASSWORD: wikimedia
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge